### ISSUE TITLE
Cruise mode

### ISSUE THREAD

**Issue by gusdabo** [eqqe/etwowconnect2#10]
Hi,
Do you know if there is a "cruise mode" available in the gt se? 
Could you make it activable within your great app?
Thanks a lot in any case

**Comment by eqqe** [comment]
I started this application looking for cruise mode, and I didn't find it in the Bluetooth controls. I think it was removed from the controller.

**Comment by gusdabo** [comment]
Thanks for your answer and the work you put in the app.
Too bad for cruise mode, tough!

Have a nice day
Guillaume d'Aboville

25 nov. 2023 11:54:57 Simon Rey ***@***.***>:
