### ISSUE TITLE
'23 GT SE 48v 10.5AH does not connect

### ISSUE THREAD

**Issue by Petivel** [eqqe/etwowconnect2#12]
it works with original etwows  app though. donno why. when i try to PAIR in settings, it just ask for a pin nr. what I do not know.

**Comment by eqqe** [comment]
What's the Bluetooth device name?

**Comment by Petivel** [comment]
in bt scanner:
Name:"E-TWOW"
dev maj class code 7936
dev class code 7936
LE

**Comment by eqqe** [comment]
Ok try to send the commands like in readme. Have you tried reinstalling the app? It's bound to only one scooter at a time.

**Comment by Petivel** [comment]
oh yeah, deleted all data, now it workz.  thx

**Comment by eqqe** [comment]
Sorry didn't expect people to have two etwow gt scooters 😂

**Comment by Petivel** [comment]
how do you sent code?

**Comment by eqqe** [comment]
See screenshot in readme

**Comment by Petivel** [comment]
yea, i saw that, but how do you get to that screen?
