### ISSUE TITLE
Some read data is incorrect

### ISSUE THREAD

**Issue by DominicHulsey-Ventive** [eqqe/etwowconnect2#5]
in lib/main.dart, for the switch statement, how did you get to the logic for converting these values?

In my testing, these all work correctly except for case 3 (lights, lock, zero start, and mode), all of which return false no matter what the scooter state is. Maybe you could help troubleshoot this?

Great work on this library by the way! It's been very helpful.

**Comment by eqqe** [comment]
What is your scooter version ? Mine is E-TWOW GT2020 and the characteristics seem to be correct.
To discover the characteristics I used the following to log them from the official app:


`objection patch apk

objection explore

com.etwowconnect on (samsung: 11) [usb] # android hooking watch class_method com.polidea.multiplatformbleadapter.BleModule.writeCharacteristicForDevice --dum
p-args `

**Comment by eqqe** [comment]
But this list of commands is for the write characteristics and your question was for the read characteristics.
I observed the characteristics sent by the scooter and somehow guessed a logic. You need to read and write in hexadecimal to understand it.
So you should read the characteristics of your scooter and let me know if the logic is different.

**Comment by DominicHulsey-Ventive** [comment]
Thank you for the quick response! I'm not very familiar with reading/writing in hexadecimal. Strange that your switch statements all work correctly except for case 3. I'll follow up if I find different logic that works!

**Comment by eqqe** [comment]
But you forgot to tell me your scooter model name?
