### ISSUE TITLE
Need Ble connections in background

### ISSUE THREAD

**Issue by Hive91** [eqqe/etwowconnect2#8]
good morning, when you change screen in multitasking, the app automatically logs out. I would need to be able to connect and leave the device connected even when you change screen to see the navigator for example.
Thank you

**Comment by eqqe** [comment]
The app will be killed by Android / IOS so the connection will be lost anyway, making it harder to reconnect because we will have to wait for the timeout of the scooter before reconnecting.

**Comment by Hive91** [comment]
Can you implement a foreground/backround Ble connection function? or is it possible to make sure that when the app is launched via macro from the screen off, it performs the connection?

**Comment by eqqe** [comment]
It's a bit complicated but I will push a new version soon that keeps the connection in the state until the app gets killed by Android.
I'll let you know.

**Comment by Petivel** [comment]
> it performs the connection?

what macroapp u usin?
